# Generated by Django 5.0 on 2023-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_pacientes',
            },
        ),
    ]
