# Generated by Django 5.0 on 2023-12-30 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('alternativa', models.TextField()),
            ],
            options={
                'db_table': 'tb_alternativas',
            },
        ),
        migrations.CreateModel(
            name='CondicaoSaude',
            fields=[
                ('id_condicao_saude', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField()),
                ('tipo', models.CharField(choices=[('sintoma', 'sintoma'), ('antecedente', 'antecedente')])),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_condicoes_saude',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_pacientes',
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('cod_icd_10', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('patologia', models.CharField()),
                ('severidade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tb_patologias',
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id_ficha_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
            options={
                'db_table': 'tb_fichas_clinicas',
            },
        ),
        migrations.CreateModel(
            name='PatologiaCondicaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_icd_10', models.ForeignKey(db_column='cod_icd_10', on_delete=django.db.models.deletion.CASCADE, to='app.patologia')),
                ('id_condicao_saude', models.ForeignKey(db_column='id_condicao_saude', on_delete=django.db.models.deletion.CASCADE, to='app.condicaosaude')),
            ],
            options={
                'db_table': 'tb_patologia_condicao',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo_resposta', models.CharField(choices=[('binaria', 'binaria'), ('categorica', 'categorica'), ('multiescolha', 'multiescolha')])),
                ('resposta_padrao', models.CharField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('id_condicao_saude', models.ForeignKey(db_column='id_condicao_saude', on_delete=django.db.models.deletion.CASCADE, to='app.condicaosaude')),
                ('id_questao_mae', models.ForeignKey(blank=True, db_column='id_questao_mae', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.questao')),
            ],
            options={
                'db_table': 'tb_questoes',
            },
        ),
        migrations.CreateModel(
            name='FichaClinicaRespostas',
            fields=[
                ('id_ficha_clinica_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('id_alternativa', models.ForeignKey(db_column='id_alternativa', on_delete=django.db.models.deletion.CASCADE, to='app.alternativa')),
                ('id_ficha_clinica', models.ForeignKey(db_column='id_ficha_clinica', on_delete=django.db.models.deletion.CASCADE, to='app.fichaclinica')),
                ('id_questao', models.ForeignKey(db_column='id_questao', on_delete=django.db.models.deletion.CASCADE, to='app.questao')),
            ],
            options={
                'db_table': 'tb_fichas_clinicas_respostas',
            },
        ),
        migrations.AddField(
            model_name='alternativa',
            name='id_questao',
            field=models.ForeignKey(db_column='id_questao', on_delete=django.db.models.deletion.CASCADE, to='app.questao'),
        ),
    ]
