# Generated by Django 5.0 on 2023-12-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField()),
                ('texto', models.TextField()),
                ('validador', models.JSONField()),
                ('tipo_resposta', models.CharField(choices=[('binaria', 'binaria'), ('categorica', 'categorica')])),
                ('resposta_padrao', models.CharField()),
                ('antecedente', models.BooleanField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('id_questao_mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.questao')),
            ],
            options={
                'db_table': 'tb_questoes',
            },
        ),
    ]
