# Generated by Django 5.0 on 2024-01-10 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='evidencia_inicial',
            field=models.ForeignKey(db_column='evidencia_inicial', default='', on_delete=django.db.models.deletion.CASCADE, to='app.condicaosaude'),
            preserve_default=False,
        ),
    ]
