from .paciente import Paciente
from .questao import Questao
from .condicaoSaude import CondicaoSaude
from .patologia import Patologia
from .patologiaCondicaoSaude import PatologiaCondicaoSaude
from .alternativa import Alternativa
from .fichaClinica import FichaClinica
from .fichaClinicaRespostas import FichaClinicaRespostas
from .diagnostico import Diagnostico
